const projects = {
  BusbetriebshofMoosach: {
    name: 'Busbetriebshof Moosach',
    location: 'München',
    year: 2017,
    yearEnd: 2018,
    architect: 'JSWD Architekten GmbH & Co. KG, Köln',
    structure: 'Reinforced Concrete',
    keywords: ['Revit', '3D-Modelling'],
    role: 'Intern',
    tasks: ['Drafting', 'Structural analysis of single members'],
    company: 'WS',
    typology: 'Infrastructure | Office',
  },
  KuwaitInternationalAirport: {
    name: 'Kuwait International Airport',
    location: 'Kuwait City',
    year: 2017,
    architect: 'Norman Foster, London',
    structure: 'Concrete and Steel Shell Structure',
    keywords: ['Rhino', 'Grasshopper'],
    role: 'Intern',
    tasks: ['Structural analysis of single members'],
    company: 'WS',
    typology: 'Infrastructure',
  },
  OneRoofGeneva: {
    name: 'One Roof Geneva',
    location: 'Genf',
    year: 2018,
    architect: 'Herzog & de Meuron, Basel',
    structure: 'Reinforced Concrete',
    keywords: [],
    role: 'Intern',
    tasks: ['Structural analysis of single members'],
    company: 'WS',
    typology: 'Office',
  },
  DasNeueAtrium: {
    name: 'Das Neue Atrium',
    location: 'Bamberg',
    year: 2019,
    yearEnd: 2020,
    yearAdditional: 2025,
    architect:
      'Bornhofen Architekten, Bamberg / Markus Rheker architecture, München',
    structure:
      'Precast Concrete (Existing Buildings) - Timber Hybrid (New Building)',
    keywords: ['Renovation'],
    role: 'Intern / Project Engineer',
    tasks: ['Structural analysis (LP4)'],
    company: 'TR',
    typology: 'Shopping',
  },
  ClimbingWalls: {
    name: 'Climbing Walls',
    location: 'Across Germany',
    year: 2019,
    architect: null,
    structure: 'Timber',
    keywords: ['SOFiSTiK', 'ComplexGeometry'],
    role: 'Intern',
    tasks: ['Structural analysis (LP4)', 'Modelling'],
    company: 'TR',
    typology: 'Sports Facility',
  },
  Kettenbrueckstraße: {
    name: 'Kettenbrückstraße',
    location: 'Bamberg',
    year: 2019,
    architect: 'Bornhofen Architekten, Bamberg',
    structure: 'Mass Timber',
    keywords: ['Renovation'],
    role: 'Intern',
    tasks: ['Structural analysis (LP2)', 'Load Take Down'],
    company: 'TR',
    typology: 'Residential',
  },
  SportCenter: {
    name: 'Sport Center',
    location: 'Regensburg',
    year: 2020,
    architect: 'Benkert Schäfer - Architekten, München',
    structure: 'Steel',
    keywords: ['Competition'],
    role: 'Junior Engineer',
    tasks: ['Structural analysis (LP1)'],
    company: 'TR',
    typology: 'Sports Facility',
  },
  InstituteForApiculture: {
    name: 'Institute for Apiculture',
    location: 'Würzburg',
    year: 2020,
    architect: 'NOVA Michael Beck Architekten, München',
    structure: 'Timber - Steel',
    keywords: ['SOFiSTiK'],
    role: 'Junior Engineer',
    tasks: ['FE-modelling'],
    company: 'TR',
    typology: 'Educational',
  },
  RenovationBroseArena: {
    name: 'Renovation Brose Arena',
    location: 'Bamberg',
    year: 2020,
    architect: 'Bornhofen Architekten, Bamberg',
    structure: 'Steel',
    keywords: ['Renovation'],
    role: 'Junior Engineer',
    tasks: ['Structural analysis (LP2-3)'],
    company: 'TR',
    typology: 'Sports Facility',
  },
  OfficeBuilding: {
    name: 'Office Building',
    location: 'Leipzig',
    year: 2022,
    yearEnd: 2023,
    architect: 'SHA Scheffler Hellbich Architekten, Dortmund',
    structure: 'Timber - Post and Beam',
    keywords: ['Rhino 3D', 'Dlubal RFEM', 'cadwork'],
    role: 'Junior Engineer',
    tasks: ['Structural analysis (LP2-LP3)'],
    company: 'BG',
    typology: 'Office',
  },
  KITAMattenberg: {
    name: 'KITA Mattenberg',
    location: 'Kassel',
    year: 2022,
    yearEnd: 2023,
    architect: 'Roller Architekten, Kassel',
    structure: 'Mass Timber',
    keywords: ['CLT', 'Renovation'],
    role: 'Junior Engineer',
    tasks: ['Structural analysis (LP4)'],
    company: 'BG',
    typology: 'Educational',
  },
  Hellerhoefe: {
    name: 'Hellerhöfe - FAZ',
    location: 'Frankfurt am Main',
    year: 2022,
    architect:
      'Schmidt Plöcker Architekten, Frankfurt am Main / kbnk Architekten, Hamburg',
    structure: 'Timber Concrete Hybrid',
    keywords: ['High Rise'],
    role: 'Junior Engineer',
    tasks: ['Modelling', 'FE-interface'],
    company: 'BG',
    typology: 'Office',
  },
  SpacioApp: {
    name: 'Spacio App',
    location: null,
    year: 2023,
    yearEnd: 2024,
    architect: null,
    structure: null,
    keywords: ['Programming', 'TypeScript', 'Generative Design'],
    role: 'Software Engineer - Developer',
    tasks: ['Programming'],
    company: 'Spacio',
    typology: 'Software Development',
  },
  AlterHafen: {
    name: 'Alter Hafen',
    location: 'Würzburg',
    year: 2024,
    yearEnd: 2025,
    architect: 'H2M Architekten + Stadtplaner GmbH, Kulmbach',
    structure: 'Timber - Steel - Concrete',
    keywords: ['Renovation'],
    role: 'Project Engineer',
    tasks: ['Structural analysis (LP2-LP3)'],
    company: 'TR',
    typology: 'Office',
  },
  Loewensaal: {
    name: 'Löwensaal',
    location: 'Nürnberg',
    year: 2024,
    architect: 'Kehrbach Planwerk GmbH & Co. KG, Nürnberg',
    structure: 'Timber Roof',
    keywords: [],
    role: 'Responsible engineer for checking',
    tasks: ['Checking'],
    company: 'TR',
    typology: 'Cultural',
  },
  BeerGarden: {
    name: 'Beer Garden',
    location: 'Erlangen',
    year: 2024,
    architect: 'PLAN@ K Architekten Kress PartGmbB, Erlangen',
    structure: 'Steel',
    keywords: [],
    role: 'Project Engineer',
    tasks: ['Structural analysis (LP1)'],
    company: 'TR',
    typology: 'Gastronomy',
  },
  BridgesLandesgartenschau: {
    name: 'Bridges Landesgartenschau',
    location: 'Bad Windsheim',
    year: 2025,
    architect: 'RMP Stephan Lenzen Landschaftsarchitekt:innen, Mannheim',
    structure: 'Steel',
    keywords: ['Parametric Design', 'Pedestrian Bridge'],
    role: 'Project Engineer',
    tasks: ['Structural analysis (LP4)'],
    company: 'TR',
    typology: 'Infrastructure | Public Space',
  },
  FacadeHeatReservoir: {
    name: 'Facade Heat Reservoir',
    location: 'Nürnberg',
    year: 2025,
    architect: 'HEIDE - Ferdinand Heide Architekten, Frankfurt am Main',
    structure: 'Steel Truss - Prestressed Cables',
    keywords: ['Grasshopper', 'Large Deformation', 'Cables'],
    role: 'Responsible engineer for checking',
    tasks: ['Checking'],
    company: 'TR',
    typology: 'Educational',
  },
  SeabridgeStripesAdidas: {
    name: 'Seabridge Stripes Adidas',
    location: 'Herzogenaurach',
    year: 2025,
    architect: null,
    structure: 'Concrete',
    keywords: ['Pedestrian Bridge'],
    role: 'Project Engineer',
    tasks: ['Structural analysis (LP2-7)'],
    company: 'TR',
    typology: 'Infrastructure',
  },
  RenovationBiggePromenade: {
    name: 'Renovation Bigge Promenade',
    location: 'Olpe',
    year: 2025,
    architect: 'club L94 Landschaftsarchitekt*innen, Köln',
    structure: 'Steel',
    keywords: ['Pedestrian Bridge'],
    role: 'Project Engineer',
    tasks: ['Structural analysis (LP2)'],
    company: 'TR',
    typology: 'Infrastructure | Public Space',
  },
  RahmerErweiterung: {
    name: 'Rahmer Erweiterung',
    location: 'Nürnberg',
    year: 2025,
    architect: 'Markus Gentner Architekten, Nürnberg',
    structure: 'Timber - Steel - Concrete (Existing Building)',
    keywords: ['Parametric Design', 'Grasshopper', 'Storey Addition'],
    role: 'Project Engineer',
    tasks: ['Structural analysis (LP2-LP4)'],
    company: 'TR',
    typology: 'Office',
  },
  Kriemhildstrasse: {
    name: 'Kriemhildstrasse',
    location: 'Nürnberg',
    year: 2025,
    architect: 'mt2 ARCHITEKTEN BDA | STADTPLANER, Nürnberg',
    structure: 'Timber',
    keywords: ['Reconstruction'],
    role: 'Project Engineer',
    tasks: ['Structural analysis (LP2-LP4)'],
    company: 'TR',
    typology: 'Residential',
  },
  Hochleistungsrechenzentrum: {
    name: 'Hochleistungsrechenzentrum',
    location: 'Erlangen',
    year: 2025,
    architect: 'Kempen Krause Ingenieure GmbH, Aachen',
    structure: 'Steel',
    keywords: ['Steel', 'Facade'],
    role: 'Responsible engineer for checking',
    tasks: ['Checking of the steel construction'],
    company: 'TR',
    typology: 'Infrastructure | Data Center',
  },
  UmbauSiedlungswerk: {
    name: 'Umbau Siedlungswerk',
    location: 'Nürnberg',
    year: 2025,
    architect: 'KÖPPEN RUMETSCH ARCHITEKTEN GmbH, Nürnberg',
    structure: 'Steel',
    keywords: ['Parametric Design'],
    role: 'Project Engineer',
    tasks: ['Parametric FE-Model'],
    company: 'TR',
    typology: 'Office',
  },
  KonradAdenauerBruecke: {
    name: 'Konrad-Adenauer-Brücke',
    location: 'Forchheim',
    year: 2025,
    architect: 'KREBS+KIEFER Ingenieure GmbH, Großostheim',
    structure: 'Steel Concrete Composite',
    keywords: ['Bridge Design'],
    role: 'Responsible engineer for checking',
    tasks: ['Checking of the bridge construction'],
    company: 'TR',
    typology: 'Infrastructuree',
  },
  ProArbeitDietzenbach: {
    name: 'ProArbeit Dietzenbach',
    location: 'Dietzenbach',
    year: 2026,
    architect: 'CARSTEN ROTH ARCHITEKT, Hamburg',
    structure: 'Timber - Hybrid',
    keywords: ['Competition'],
    role: 'Project Engineer',
    tasks: ['Structural analysis (LP1)'],
    company: 'TR',
    typology: 'Office',
  },
  Supersonic: {
    name: 'Supersonic',
    location: 'Roth',
    year: 2026,
    artist: 'Sebastian Kuhn',
    structure: 'Folded steel structure',
    keywords: ['Art installation'],
    role: 'Project Engineer',
    tasks: ['FE-Postprocessing'],
    company: 'TR',
    typology: 'Art Installation',
  },
}

export { projects }
